// Assembly-only meals. Cooked grains/legumes and tofu must be bought ready
// to eat; the stated time does not pretend that cooking raw ingredients is free.
module.exports = [
  { id:'simple-soy-oats-banana', en:'Soy milk, oats and banana', he:'חלב סויה, שיבולת שועל ובננה', slots:['breakfast','snack'], diet:'vegan', items:[['soy-milk',250],['oats',60],['banana',120]], prepEn:'Combine instant rolled oats with soy milk and sliced banana. No cooking required.', prepHe:'מערבבים שיבולת שועל אינסטנט עם חלב סויה ובננה חתוכה. ללא בישול.' },
  { id:'simple-soy-oats-apple', en:'Soy milk, oats, apple and peanuts', he:'חלב סויה, שיבולת שועל, תפוח וחמאת בוטנים', slots:['breakfast','snack'], diet:'vegan', items:[['soy-milk',250],['oats',55],['apple',150],['peanut-butter',20]], prepEn:'Combine instant rolled oats, soy milk, apple and peanut butter.', prepHe:'מערבבים שיבולת שועל אינסטנט, חלב סויה, תפוח וחמאת בוטנים.' },
  { id:'simple-peanut-banana-bread', en:'Peanut butter bread, banana and soy milk', he:'לחם עם חמאת בוטנים, בננה וחלב סויה', slots:['breakfast','snack'], diet:'vegan', items:[['whole-wheat-bread',90],['peanut-butter',25],['banana',120],['soy-milk',250]], prepEn:'Spread peanut butter on bread. Serve with banana and soy milk.', prepHe:'מורחים חמאת בוטנים על לחם ומגישים עם בננה וחלב סויה.' },
  { id:'simple-tofu-hummus-pita', en:'Tofu and hummus pita', he:'פיתה עם טופו וחומוס', slots:['breakfast','lunch','dinner'], diet:'vegan', items:[['tofu',200],['pita',90],['hummus',70],['cucumber',100]], prepEn:'Use ready-to-eat tofu according to its package instructions. Fill pita with tofu, hummus and cucumber.', prepHe:'משתמשים בטופו מוכן לאכילה לפי הוראות האריזה. ממלאים פיתה בטופו, חומוס ומלפפון.' },
  { id:'simple-tofu-ready-rice', en:'Tofu, ready rice and cucumber', he:'טופו, אורז מוכן ומלפפון', slots:['lunch','dinner'], diet:'vegan', items:[['tofu',230],['white-rice',220],['cucumber',120],['olive-oil',8]], prepEn:'Use ready-to-eat tofu and already-cooked rice. Heat only if the package requires it, then serve with cucumber and oil.', prepHe:'משתמשים בטופו מוכן לאכילה ובאורז שכבר בושל. מחממים רק לפי הוראות האריזה ומגישים עם מלפפון ושמן.' },
  { id:'simple-chickpea-tofu-salad', en:'Chickpea, tofu and tomato plate', he:'צלחת חומוס, טופו ועגבנייה', slots:['lunch','dinner'], diet:'vegan', items:[['chickpeas',170],['tofu',200],['tomato',150],['whole-wheat-bread',75]], prepEn:'Drain cooked canned chickpeas. Combine with ready-to-eat tofu and tomato; serve with bread.', prepHe:'מסננים גרגירי חומוס מבושלים משימורים. משלבים עם טופו מוכן לאכילה ועגבנייה ומגישים לצד לחם.' },
  { id:'simple-bean-tofu-bread', en:'White beans, tofu and bread', he:'שעועית לבנה, טופו ולחם', slots:['lunch','dinner'], diet:'vegan', items:[['white-beans',180],['tofu',200],['whole-wheat-bread',80],['tomato',120]], prepEn:'Drain cooked canned beans. Serve with ready-to-eat tofu, bread and tomato.', prepHe:'מסננים שעועית מבושלת משימורים ומגישים עם טופו מוכן לאכילה, לחם ועגבנייה.' },
  { id:'simple-lentil-tofu-rice', en:'Lentils, tofu and ready rice', he:'עדשים, טופו ואורז מוכן', slots:['lunch','dinner'], diet:'vegan', items:[['lentils',180],['tofu',180],['white-rice',160],['cucumber',120]], prepEn:'Combine already-cooked lentils and rice with ready-to-eat tofu. Follow package heating instructions and add cucumber.', prepHe:'משלבים עדשים ואורז שכבר בושלו עם טופו מוכן לאכילה. מחממים לפי הוראות האריזה ומוסיפים מלפפון.' }
].map(meal => ({...meal, format:'quick', minutes:5, styles:['supermarket']}));
